### ISSUE TITLE
No bucket filling machine ?

### ISSUE THREAD

**Issue by Asshall** [AllTheMods/ATM-4#116]
I mean, I've been at this for a while now, but for the life of me I can't find a machine capable of filling a bucket through @refinedstorage... I think I'm not missing anything else... ( https://refinedstorage.raoulvdberge.com/wiki/autocrafting-with-filled-buckets ). I either get "No machine found" when using @silent'smechanism's machines or "Machines doesn't accept item"  on the rest. 

If there is any @refinedstorage experts here maybe I'm doing something wrong, if not maybe we need a bucket filling machine...

**Comment by LezChap** [comment]
Seems broken, can't get it to work despite creating multiple machines that will do the job if I give it a bucket manually.  I think it's a bug with RefinedStorage, not seeing anything on their issue tracker, so I suggest you open it up there: https://github.com/raoulvdberge/refinedstorage/issues

**Comment by Asshall** [comment]
What machines have you tried ? I don't want to open an issue over there without testing it myself...

**Comment by Asshall** [comment]
I think it is a modpack problem and we just don't have the right machines. 
If you make a pattern for diesel made with oil and bucket and use a @silentmechanism's refinery it inputs oil in the right slot and outputs a diesel bucket but simply doesn't retrieve it...

**Comment by LezChap** [comment]
The recipe in the link above...a pattern recipe of 1000mb of water + 1 empty bucket = 1 water bucket.  When put in a crafter, it should place the bucket in whatever inventory the crafter is pointing towards, regardless of if it's a chest (that pumps into a system) or a machine (like an autoclicker, a tank that fills buckets, or anything else).  It doesn't export the bucket on demand via the crafter...nothing happens.

If you use a machine that'll fill the bucket, like an autoclicker, with an import filtered for water buckets, it still doesn't work.  Also tried dispensers, using a chest as an intermediary (could be the clicker didn't accept items from automated input due to how it was coded), nothing worked.

**Comment by Asshall** [comment]
I think one of us is misunderstanding the way it works, for me you provide both liquid and a bucket to a machine. The machine need an internal buffer to contain the liquid and a slot to input a bucket that will be turned into a filled bucket of whatever liquid is in the buffer. 
In my tests both the liquid and the bucket get exported in the machine. 

In your test with the autoclicker did you use a crafting upgrade ? I don't get it...

**Comment by Asshall** [comment]
So I found a very ugly workaround... 
Crafter pointing towards an autoclicker. Pattern is empty bucker = filled bucket. Have a liquid source in front of the autoclicker and a Xnet network extracting said liquid buckets it. 
Then export Xnet items to RefinedStorage through a buffer chest...

**Comment by Asshall** [comment]
I guess you can use the RefinedStorage block placer to create the liquid source... Still very ugly ^^

**Comment by LezChap** [comment]
Alright, I figured out a system to make buckets from fluids, but it requires (per fluid):

- 1 tank from RFToolsUtility
- 1 importer
- 1 crafter
- 1 pattern that says: 1 empty bucket to 1 bucket of said fluid.
- 1 exporter or external storage
- 1 autoclicker

Set it up like this: ![https://i.imgur.com/ytXanSq.png](https://i.imgur.com/ytXanSq.png)
Exporter needs to list the fluid, or if it's an external storage set it to whitelist the fluid with a high priority.  Exporter will mean you won't see 32 buckets of the fluid in your system, but it'll be available to craft...so when you're running low, you won't know it until the craft fails.  External storage requires the priority and whitelisting to be clicked (a little more setup), but you'll see the fluid in your Fluid Grid.  Importer will be whitelist the bucket of fluid.  In the example above, I used Water because it's easy to make infinite.  The autoclicker is set on speed 6 (once every 10 ticks)...faster and it clicks before the importer can pick up the bucket (this may be able to be faster if you use speed upgrades).

Silent's Mechanisms' Machines are notorious for handling automated fluid transferring poorly.  If you try to import with a whitelist, and that fluid is in the machine, it'll do a pull...but it won't respect the whitelist when it pulls, as it seems to pull from the first available tank (when looking at the GUI  the tanks are "numbered" from left to right).  So, if you whitelist diesel, from the refinery, then fill it with oil, after the first bucket of oil processes it'll see there's diesel, try to import, but actually import the oil.  I don't know of any way around this currently without doing a super, duper, complicated setup that only moves a bucket at a time and knows to wait until the processing is done before importing, then emptying all fluids.  When trying with Xnet, if you had the controller handling multiple fluids, even on different channels, it'd put fluid from the first channel into an import on the second....it wasn't pretty trying to clear water out of a refinery (for example).

**Comment by Asshall** [comment]
Yep we got the same idea ^^ Yours more refined tho ^^ You forgot the autoclicker in you list ;)

**Comment by Asshall** [comment]
So is that a refinedstorage bug or rather a lack of a bucket filling machine ?
I would say it is a bug because this functionnality should not rely on third party machines and RefinedStorage should have said machine...

**Comment by LezChap** [comment]
> So is that a refinedstorage bug or rather a lack of a bucket filling machine ?

Looks like a lack of a block/machine/device that accepts both a fluid and an empty bucket at the same time.  Though I agree with you, if you have a recipe with a bucket of fluid in a pattern, and the refined storage system has both an empty bucket and the fluid available, it should auto-fill the bucket internally...like how if you click a fluid on a Fluid Grid and have a bucket in the system, it uses the bucket to give you a bucket of the fluid.

**Comment by Asshall** [comment]
Do you wanna post and issue on the RefinedStorage's github ? I would do it but seeing your profile you look more concerned by RefinedStorage ;)

**Comment by LezChap** [comment]
I'll work on the post now.

**Comment by LezChap** [comment]
Not going to happen, and I fully disagree with the dev in this case: https://github.com/raoulvdberge/refinedstorage/issues/2395

**Comment by Asshall** [comment]
Well that's a shame... So this issue will stay open... @whatthedrunk can we have your feedback ?

**Comment by LezChap** [comment]
I think this will be our solution: https://www.curseforge.com/minecraft/mc-mods/really-simple-tanks

hopefully will be added to the next pack update. :)

**Comment by LezChap** [comment]
It was added to the pack update yesterday (0.3.2 iirc).  Try it out and close this if it works for you? :)

**Comment by Asshall** [comment]
Sorry for the late response, I've been afk for some time. I got a weird save breaking bug due to the last update, being the dum dum I am I lost my save sooo.. I'll take your word for it ;)
