### ISSUE TITLE
Crash when loading chunks with simple storage network

### ISSUE THREAD

**Issue by Stray216** [AllTheMods/ATM-4#12]
Whenever i leave my base and come back, as soon as the chunks with the storage network load, it crashes my game. I tried chunkloading the storage network but that didn't solve it.

Crash Report: https://pastebin.com/gimwe8wT

I'm not good at deciphering crash reports but it does say "storagenetwork" and "TileCableWithFacing" and something with neighbours and direction.

So here's a picture of the cables: https://imgur.com/a/jyQd1n8

**Comment by Stray216** [comment]
So apparently it just stopped happening.

**Comment by Stray216** [comment]
It happened again, crash reports looks similar.
Crash Report: https://pastebin.com/ApeQ4V0k

**Comment by drizzs** [comment]
java.lang.NullPointerException: Ticking block entity
    at com.lothrazar.storagenetwork.api.data.DimPos.<init>(DimPos.java:44) ~[?:1.14.4-0.0.11] {}
    at com.lothrazar.storagenetwork.block.TileConnectable.getDimPos(TileConnectable.java:36) ~[?:1.14.4-0.0.11] {}
    at com.lothrazar.storagenetwork.block.TileConnectable.func_174878_a(TileConnectable.java:42) ~[?:1.14.4-0.0.11] {}

this for sure indicates the issue is with storagenetwork. It could be a compatibility issue with another mod so i suggest you try repeating this without any mods to make sure but i'd report this to the mod creators! This issue is not something the ATM team can help as they have no control over the source code of Storage Network!


-- Block entity being ticked --
Details:
    Name: storagenetwork:storage_kabel // com.lothrazar.storagenetwork.block.cablelink.TileCableLink
    Block: Block{storagenetwork:storage_kabel}[down=cable,east=none,north=cable,south=cable,up=inventory,west=cable]
    Block location: World: (-187,66,-18), Chunk: (at 5,4,14 in -12,-2; contains blocks -192,0,-32 to -177,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Block: Block{storagenetwork:storage_kabel}[down=cable,east=none,north=cable,south=cable,up=inventory,west=cable]
    Block location: World: (-187,66,-18), Chunk: (at 5,4,14 in -12,-2; contains blocks -192,0,-32 to -177,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
    at net.minecraft.world.World.func_217391_K(World.java:621)
    at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:148)
 

This is whats being ticked its a cable link thats the issue. The location is also there you should be able to find out which it is!

As for how to fix it, the mod creators would also be the best people to ask!

**Comment by Stray216** [comment]
Thank you, that's very helpful! Didn't notice there were actual coordinates.
